### ISSUE TITLE
Mod crashes server whenever a creeper explodes

### ISSUE THREAD

**Issue by Namine13** [Virtuoel/WhiteRabbit#1]
To me this seems like something that makes no sense, i don't know how this is coded, but every-time i have this mod installed, and a creeper explodes, at the moment of detonation the server crashes. Attached is the latest crash file, if theres anything that can be done to remedy this please let me know, i was really looking forward to running this mod on my server. :(

[crash-2020-07-13_22.42.40-server.txt](https://github.com/Virtuoel/WhiteRabbit/files/4916217/crash-2020-07-13_22.42.40-server.txt)

**Comment by Namine13** [comment]
[crash-2020-07-15_16.47.32-server.txt](https://github.com/Virtuoel/WhiteRabbit/files/4927795/crash-2020-07-15_16.47.32-server.txt)
Running only your mod, Pehkui and the Fabric.api results in the same problem

**Comment by sean-work** [comment]
I don't have a crashlog anymore but I did have this same issue referencing Pehkui-refmap.json and the only mod i had with a Pehkui jar embedded was White Rabbit. After removing the mod, creepers no longer crash my server. Huge shame as I absolutely love the mod! I'll have to mess with it in singleplayer instead for now. Thanks for the mod.
