### ISSUE TITLE
dispenser crash the game

### ISSUE THREAD

**Issue by paille-boy** [Virtuoel/WhiteRabbit#2]
so i try to resize a wolf in creative to see how it work and wen i activate the dispenser with the resizing food it crash the game :/ i play on 1.16.4

also its nice yu made this mod i hope yu will make more like food that make yu grow 0.25 0.5 or 0.75 and food that change yur motion so yu don't have to struggle with yur speed and jump wennever yu change size

**Comment by Virtuoel** [comment]
Closed by a5eb560d5564a54ca7ae093f60cc5366356aa4b4
